import React from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '../lib/AntdRegistry';
import Providers from './Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <Providers>
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
      </Providers>
    </body>
  </html>
);

export default RootLayout;